name: PulleyLabs
favicon: null
layout_spectrum: 0.9186448447871953
typography_spectrum: 0.58931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e3e60'
    - '#b4bfd1'
    - '#0c1631'
    - '#627293'
    - '#d1dbe4'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
